# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.Hour')),
            ],
        ),
        migrations.CreateModel(
            name='Washroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='washroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.Washroom'),
        ),
    ]
